
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, min_ios_version_supported

prepare_react_native_project!

ENV['USE_FRAMEWORKS'] ||= 'static'
use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym

target 'gtaApp' do
  config = use_native_modules!

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

        # Lottie fix
        if target.name == 'lottie-ios'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end

        # MultiplatformBleAdapter fix
        if target.name == 'MultiplatformBleAdapter'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
          config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
        end
      end
    end
  end
end
